Update production.yml

diff --git a/.github/workflows/production.yml b/.github/workflows/production.yml
--- a/.github/workflows/production.yml
+++ b/.github/workflows/production.yml
@@ -4,7 +4,7 @@ on:
   push:
     branches:
       - main
-      
+
 jobs:
   deploy:
     runs-on: self-hosted
@@ -12,7 +12,7 @@ jobs:
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
-        
+
       - name: Stop and Remove Existing Container (if running)
         run: |
           CONTAINER_ID=$(docker ps -q --filter "name=fry-network-backend")
@@ -27,9 +27,9 @@ jobs:
       - name: Build & Run Docker Container
         run: |
           cd /home/actionsuser/production_Env/actions-runner-prod/fry-network/fry-market-backend/fry-market-backend || { echo "Project folder not found!"; exit 1; }
-          docker build -t fry-network  .
+          docker build -t fry-network .
           docker run -d -p 6000:6000 --name=fry-network-backend fry-network
-          
+
       - name: Cleanup Old Docker Images
         run: |
           echo "Removing old unused Docker images..."
@@ -41,12 +41,17 @@ jobs:
     needs: deploy
 
     steps:
+      - name: Debug Whoami + Sudo Permissions
+        run: |
+          echo "Running as: $(whoami)"
+          sudo -l
+
       - name: Test nginx config
         run: |
           echo "Checking nginx config..."
-          bash -c "sudo -n /usr/sbin/nginx -t || { echo '❌ Nginx test failed due to sudo permissions'; exit 1; }"
+          sudo -n /usr/sbin/nginx -t || { echo '❌ Nginx test failed due to sudo permissions'; exit 1; }
 
       - name: Restart nginx
         run: |
           echo "Restarting nginx..."
-          bash -c "sudo -n /bin/systemctl restart nginx || { echo '❌ Failed to restart nginx due to sudo permissions'; exit 1; }"
+          sudo -n /bin/systemctl restart nginx || { echo '❌ Failed to restart nginx due to sudo permissions'; exit 1; }
