Update production.yml

diff --git a/.github/workflows/production.yml b/.github/workflows/production.yml
--- a/.github/workflows/production.yml
+++ b/.github/workflows/production.yml
@@ -49,7 +49,7 @@ jobs:
       - name: Test nginx config
         run: |
           echo "Checking nginx config..."
-          sudo -n /usr/sbin/nginx -t || { echo '❌ Nginx test failed due to sudo permissions'; exit 1; }
+          sudo -n /usr/sbin/nginx -t || { echo '❌ Nginx test failed due to sudo permissions'; exit 1; } 
 
       - name: Restart nginx
         run: |
